//types of actions

//products
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
const ADD_PRODUCT = 'ADD_PRODUCT'
const DELETE_PRODUCT = 'DELETE_PRODUCT'
const EDIT_PRODUCT = 'EDIT_PRODUCT'
const FETCH_PRODUCTS_BY_TYPE_SUCCESS = 'FETCH_PRODUCTS_BY_TYPE_SUCCESS'

//product types
const FETCH_PRODUCT_TYPES_SUCCESS = 'FETCH_PRODUCT_TYPES_SUCCESS'
const ADD_PRODUCT_TYPE = 'ADD_PRODUCT_TYPE'
const DELETE_PRODUCT_TYPE = 'DELETE_PRODUCT_TYPE'
const EDIT_PRODUCT_TYPE = 'EDIT_PRODUCT_TYPE'


//product types

export default {
	FETCH_PRODUCTS_SUCCESS,
	ADD_PRODUCT,
	DELETE_PRODUCT,
	EDIT_PRODUCT,
	FETCH_PRODUCTS_BY_TYPE_SUCCESS,
	FETCH_PRODUCT_TYPES_SUCCESS,
	ADD_PRODUCT_TYPE,
	DELETE_PRODUCT_TYPE,
	EDIT_PRODUCT_TYPE
}
